import type { EquipmentSlot, ShopItem } from "./types.js";

export type EquipmentShopItem = ShopItem & { slot: EquipmentSlot };

export const EQUIPMENT_CATALOG: EquipmentShopItem[] = [
  { id: "ew_beer_chucks", slot: "weapon", name: "Öl-nunchucks", price: 14, power: 2, randomOtherDamageOnWin: 1 },
  { id: "ew_fathammare", slot: "weapon", name: "Fathammare", price: 13, power: 2, pvpDieBonus: 1 },
  { id: "ew_can_opener", slot: "weapon", name: "Flasköppnare", price: 10, power: 1, gainGoldOnWin: 1 },
  {
    id: "ew_can_sword",
    slot: "weapon",
    name: "Burksvärd",
    price: 13,
    power: 1,
    powerAtGold10: 2,
    powerAtGold20: 3,
    powerAtGold30: 4,
    powerDynamicMax: 4,
  },
  { id: "ew_padel", slot: "weapon", name: "Mäskpaddel", price: 9, power: 1 },
  { id: "ew_humleklubba", slot: "weapon", name: "Humleklubba", price: 12, power: 1, pvpDieBonus: 2 },
  { id: "ew_doublepipe", slot: "weapon", name: "Dubbelpipa", price: 15, power: 2, sipAttackBonus: 3 },
  { id: "ew_singlepipe", slot: "weapon", name: "Enkelpipa", price: 11, power: 1, sipAttackBonus: 2 },
  { id: "eh_cap_front", slot: "helmet", name: "Keps", price: 7, damageNegate: 1 },
  { id: "eh_cap_back", slot: "helmet", name: "Bakåtvänd keps", price: 8, combatBonus: 1 },
  { id: "eh_glass_helmet", slot: "helmet", name: "Glashjälm", price: 11, negateAllOnce: true },
  { id: "eh_foamvisor", slot: "helmet", name: "Skumvisir", price: 11, damageNegate: 1, combatBonus: 1, penaltySipExtra: 1 },
  { id: "eh_beanie", slot: "helmet", name: "Beanie", price: 10, damageNegate: 2 },
  { id: "eh_beer_cap_helm_1", slot: "helmet", name: "Burkhjälm", price: 12, damageNegate: 3 },
  {
    id: "eh_beer_cap_helm_2",
    slot: "helmet",
    name: "Burkhjälm II",
    price: 13,
    damageNegate: 3,
    bossDamageNegateBonus: 1,
  },
  {
    id: "eh_beer_filled_helmet",
    slot: "helmet",
    name: "Ölfylld rymdhjälm",
    price: 12,
    combatBonus: 1,
    klunkAttackBonus10: 2,
    klunkAttackBonus20: 3,
    klunkAttackBonusMax: 3,
  },
  { id: "ex_buckler", slot: "accessory", name: "Pilsnersköld", price: 8, damageNegate: 1 },
  { id: "ex_gold_chain", slot: "accessory", name: "Guldkedja", price: 9, gainGoldPerCombat: 1 },
  { id: "ex_beer_cape", slot: "accessory", name: "Mantel", price: 9, canSkipMonsterEncounter: true },
  { id: "ex_sunglasses", slot: "accessory", name: "Solbrillor", price: 8, preventTheft: true },
  { id: "ex_tapkey", slot: "accessory", name: "Taproom nyckel", price: 7, levelUpDiscountGold: 10 },
  { id: "ex_ring", slot: "accessory", name: "Ring", price: 10, combatBonus: 2, damageNegate: -2 },
  {
    id: "ex_black_belt",
    slot: "accessory",
    name: "Svart bälte",
    price: 10,
    combatBonus: 1,
    gainKlunkPerCombat: 1,
  },
  { id: "ea_cap_bikini", slot: "armor", name: "Kapsylbikini", price: 9, bonusHp: 0, damageNegate: 1, pvpCannotBeChallenged: true },
  { id: "ea_tshirt", slot: "armor", name: "T-shirt", price: 8, bonusHp: 0, damageNegate: 1 },
  { id: "ea_hoodie", slot: "armor", name: "Hoodie", price: 10, bonusHp: 0, damageNegate: 2 },
  { id: "ea_six_pack", slot: "armor", name: "Sexpack", price: 11, bonusHp: 0, damageNegate: 1, gainGoldOnDamageTaken: 1 },
  { id: "ea_beer_barrel", slot: "armor", name: "Öltunna", price: 13, bonusHp: 0, damageNegate: 3 },
  { id: "ea_can_armor", slot: "armor", name: "Burkrustning", price: 14, bonusHp: 0, damageNegate: 3, bossDamageNegateBonus: 1 },
];

