import type { EquipmentSlot, ShopItem } from "./types.js";

export type EquipmentShopItem = ShopItem & { slot: EquipmentSlot };

export const EQUIPMENT_CATALOG: EquipmentShopItem[] = [
  {
    id: "ew_beer_chucks",
    slot: "weapon",
    name: "Öl-nunchucks",
    price: 14,
    power: 2,
    randomOtherDamageOnWin: 1,
    rulesText: "När du vinner en strid snurrar nunchucksen vidare — en slumpad annan bryggare tar lite stryk.",
  },
  {
    id: "ew_fathammare",
    slot: "weapon",
    name: "Fathammare",
    price: 13,
    power: 2,
    pvpDieBonus: 1,
    rulesText: "Tung hammare: extra kraft i bryggare-mot-bryggare när tärningen ska avgöra.",
  },
  {
    id: "ew_can_opener",
    slot: "weapon",
    name: "Flasköppnare",
    price: 10,
    power: 1,
    gainGoldOnWin: 1,
    rulesText: "Praktiskt vapen: efter vunnet monster får du lite pant tillbaka.",
  },
  {
    id: "ew_can_sword",
    slot: "weapon",
    name: "Burksvärd",
    price: 13,
    power: 1,
    powerAtGold10: 2,
    powerAtGold20: 3,
    powerAtGold30: 4,
    powerDynamicMax: 4,
    rulesText: "Ju mer pant du burit, desto vassare blir klingan — upp till en maxgräns.",
  },
  {
    id: "ew_padel",
    slot: "weapon",
    name: "Mäskpaddel",
    price: 9,
    power: 1,
    rulesText: "Enkel men pålitlig — +1 attack i monsterstrid.",
  },
  {
    id: "ew_humleklubba",
    slot: "weapon",
    name: "Humleklubba",
    price: 12,
    power: 1,
    pvpDieBonus: 2,
    rulesText: "",
  },
  {
    id: "ew_doublepipe",
    slot: "weapon",
    name: "Dubbelpipa",
    price: 15,
    power: 2,
    sipAttackBonus: 1,
    rulesText: "Monsterstrid: du kan ta en straffklunk före slaget för +1 attack.",
  },
  {
    id: "ew_singlepipe",
    slot: "weapon",
    name: "Enkelpipa",
    price: 11,
    power: 1,
    sipAttackBonus: 1,
    rulesText: "Monsterstrid: valfri straffklunk före slaget ger +1 attack.",
  },
  {
    id: "eh_cap_front",
    slot: "helmet",
    name: "Keps",
    price: 7,
    damageNegate: 1,
    rulesText: "Skärmen skyddar — lite mindre HP-skada per träff.",
  },
  {
    id: "eh_cap_back",
    slot: "helmet",
    name: "Bakåtvänd keps",
    price: 8,
    combatBonus: 1,
    rulesText: "Nu ser du lite yngre ut",
  },
  {
    id: "eh_glass_helmet",
    slot: "helmet",
    name: "Glashjälm",
    price: 11,
    negateAllOnce: true,
    rulesText: "En gång per strud: första gången du skulle ta skada i monsterstrid blockeras allt.",
  },
  {
    id: "eh_foamvisor",
    slot: "helmet",
    name: "Skumvisir",
    price: 11,
    damageNegate: 1,
    combatBonus: 1,
    penaltySipExtra: 1,
    rulesText: "Skum och stil — men straffklunkar kladdar lite extra på dig.",
  },
  {
    id: "eh_beanie",
    slot: "helmet",
    name: "Beanie",
    price: 10,
    bonusHp: 2,
    damageNegate: 1,
    rulesText: "Mysig mössa: lite mer liv och lättare att stå emot smällar.",
  },
  {
    id: "eh_beer_cap_helm_1",
    slot: "helmet",
    name: "Burkhjälm",
    price: 12,
    damageNegate: 0,
    rulesText:
      "Del av burk-setet: +1 / +2 / +3 attack i strid beroende på hur många burk-delar du har utrustat (rustning, hjälm, sköld).",
  },
  {
    id: "eh_beer_cap_helm_2",
    slot: "helmet",
    name: "Legendarisk Burkhjälm",
    price: 25,
    damageNegate: 3,
    rulesText: "Ger −4 skada per träff när du har minst 15 klunkar — annars ingen reduktion.",
  },
  {
    id: "eh_beer_filled_helmet",
    slot: "helmet",
    name: "Ölfylld rymdhjälm",
    price: 12,
    combatBonus: 1,
    klunkAttackBonus10: 1,
    klunkAttackBonus20: 2,
    klunkAttackBonusMax: 3,
    rulesText: "Ju mer du burit desto hårdare slår du — upp till en maxbonus.",
  },
  {
    id: "ex_buckler",
    slot: "accessory",
    name: "Burksköld",
    price: 8,
    damageNegate: 0,
    rulesText:
      "Del av burk-setet: +1 / +2 / +3 sköld (skadereduktion) beroende på hur många burk-delar du har utrustat.",
  },
  {
    id: "ex_gold_chain",
    slot: "accessory",
    name: "Guldkedja",
    price: 9,
    gainGoldPerCombat: 1,
    rulesText: "Bling vid varje monsterstrid: lite pant när striden tar fart.",
  },
  {
    id: "ex_beer_cape",
    slot: "accessory",
    name: "Mantel",
    price: 9,
    canSkipMonsterEncounter: true,
    rulesText: "Skippa dålig batch. En dramatikens mästare. Ena sekunden är du där, nästa är du i kebabkön.",
  },
  {
    id: "ex_sunglasses",
    slot: "accessory",
    name: "Solbrillor",
    price: 8,
    preventTheft: true,
    rulesText: "Ingen ser vad du har: andra kan inte stjäla dina prylar eller pant med stöld-effekter, och du skyddas vid BvB-byte.",
  },
  {
    id: "ex_tapkey",
    slot: "accessory",
    name: "Taproom nyckel",
    price: 7,
    levelUpDiscountGold: 10,
    rulesText: "VIP till nästa våning: billigare nivå upp i pant.",
  },
  {
    id: "ex_ring",
    slot: "accessory",
    name: "Ring",
    price: 10,
    combatBonus: 2,
    damageNegate: -2,
    rulesText: "Priset för makt mäts sällan i guld, utan i blod. Är du redo att betala?",
  },
  {
    id: "ex_black_belt",
    slot: "accessory",
    name: "Svart bälte",
    price: 10,
    combatBonus: 1,
    gainKlunkPerCombat: 1,
    rulesText:
      "Svart bälte i karatefylle: när en monsterstrid börjar läggs +1 straffklunk på din klunkräknare (gäller inte BvB).",
  },
  {
    id: "ea_cap_bikini",
    slot: "armor",
    name: "Kapsylbikini",
    price: 9,
    bonusHp: 0,
    damageNegate: 1,
    pvpCannotBeChallenged: true,
    rulesText: "Avslappnad look: du kan inte utmanas till BvB, men du kan fortfarande utmana andra.",
  },
  {
    id: "ea_tshirt",
    slot: "armor",
    name: "T-shirt",
    price: 8,
    bonusHp: 0,
    damageNegate: 1,
    rulesText: "Basplagg med lätt skydd.",
  },
  {
    id: "ea_hoodie",
    slot: "armor",
    name: "Hoodie",
    price: 10,
    bonusHp: 0,
    damageNegate: 2,
    rulesText: "Mjuk och tjock — bättre skydd mot träffar.",
  },
  {
    id: "ea_six_pack",
    slot: "armor",
    name: "Sexpack",
    price: 11,
    bonusHp: 0,
    damageNegate: 1,
    gainGoldOnDamageTaken: 1,
    rulesText: "När du tar skada rullar en burk ut — lite pant som tröst.",
  },
  {
    id: "ea_beer_barrel",
    slot: "armor",
    name: "Öltunna",
    price: 13,
    bonusHp: 0,
    damageNegate: 2,
    healHpPerTurn: 1,
    rulesText: "Stadig sköld och lite läckande öl: +1 HP vid varje turstart (upp till max HP).",
  },
  {
    id: "ea_can_armor",
    slot: "armor",
    name: "Burkrustning",
    price: 14,
    bonusHp: 0,
    damageNegate: 0,
    rulesText:
      "Del av burk-setet: +2 / +4 / +10 max HP beroende på hur många burk-delar du har utrustat.",
  },
];

