import type { EquipmentSlot, ShopItem } from "./types.js";

export type EquipmentShopItem = ShopItem & { slot: EquipmentSlot };

export const EQUIPMENT_CATALOG: EquipmentShopItem[] = [
  {
    id: "ew_beer_chucks",
    slot: "weapon",
    name: "Öl-nunchucks",
    price: 14,
    power: 2,
    randomOtherDamageOnWin: 1,
    rulesText: "När du vinner en strid snurrar nunchucksen vidare — en slumpad annan bryggare tar lite stryk.",
  },
  {
    id: "ew_fathammare",
    slot: "weapon",
    name: "Fathammare",
    price: 13,
    power: 2,
    pvpDieBonus: 1,
    rulesText: "Tung hammare: extra kraft i bryggare-mot-bryggare när tärningen ska avgöra.",
  },
  {
    id: "ew_can_opener",
    slot: "weapon",
    name: "Flasköppnare",
    price: 10,
    power: 1,
    gainGoldOnWin: 1,
    rulesText: "Praktiskt vapen: efter vunnet monster får du lite pant tillbaka.",
  },
  {
    id: "ew_can_sword",
    slot: "weapon",
    name: "Burksvärd",
    price: 13,
    power: 1,
    powerAtGold10: 2,
    powerAtGold20: 3,
    powerAtGold30: 4,
    powerDynamicMax: 4,
    rulesText: "Ju mer pant du burit, desto vassare blir klingan — upp till en maxgräns.",
  },
  {
    id: "ew_padel",
    slot: "weapon",
    name: "Mäskpaddel",
    price: 9,
    power: 1,
    rulesText: "Enkel men pålitlig — +1 attack i monsterstrid.",
  },
  {
    id: "ew_humleklubba",
    slot: "weapon",
    name: "Humleklubba",
    price: 12,
    power: 1,
    pvpDieBonus: 2,
    rulesText: "",
  },
  {
    id: "ew_empty_bottle",
    slot: "weapon",
    name: "Tom flaska",
    price: 12,
    power: 5,
    breakOnWin: true,
    rulesText: "Ger hög kraft men går sönder direkt efter att du vunnit en strid.",
  },
  {
    id: "ew_doublepipe",
    slot: "weapon",
    name: "Dubbelpipa",
    price: 15,
    power: 2,
    sipAttackBonus: 1,
    rulesText: "Ta en straffklunk före tärningsslaget för +1 attack.",
  },
  {
    id: "ew_singlepipe",
    slot: "weapon",
    name: "Enkelpipa",
    price: 11,
    power: 1,
    sipAttackBonus: 1,
    rulesText: "Ta en straffklunk före tärningsslaget för +1 attack.",
  },
  {
    id: "eh_cap_front",
    slot: "helmet",
    name: "Keps",
    price: 7,
    damageNegate: 1,
    rulesText: "Skärmen skyddar — lite mindre HP-skada per träff.",
  },
  {
    id: "eh_cap_back",
    slot: "helmet",
    name: "Bakåtvänd keps",
    price: 8,
    combatBonus: 1,
    rulesText: "Nu ser du lite yngre ut",
  },
  {
    id: "eh_glass_helmet",
    slot: "helmet",
    name: "Glashjälm",
    price: 11,
    negateAllOnce: true,
    rulesText: "Blockerar all skada en gång, går sedan sönder.",
  },
  {
    id: "eh_keykeg_helmet",
    slot: "helmet",
    name: "Keykeghjälm",
    price: 12,
    combatBonus: -1,
    damageNegate: 2,
    rulesText: "Stabil hjälm med starkt skydd, men den tynger dina slag.",
  },
  {
    id: "eh_foamvisor",
    slot: "helmet",
    name: "Skumvisir",
    price: 11,
    damageNegate: 1,
    combatBonus: 1,
    penaltySipExtra: 1,
    rulesText: "Skum och stil — men straffklunkar kladdar lite extra på dig.",
  },
  {
    id: "eh_beanie",
    slot: "helmet",
    name: "Beanie",
    price: 10,
    bonusHp: 2,
    damageNegate: 1,
    rulesText: "Mysig mössa: lite mer liv och lättare att stå emot smällar.",
  },
  {
    id: "eh_beer_cap_helm_1",
    slot: "helmet",
    name: "Burkhjälm",
    price: 12,
    damageNegate: 0,
    rulesText:
      "Burkset bonus: +1 / +2 / +3 attack i strid.",
  },
  {
    id: "eh_beer_cap_helm_2",
    slot: "helmet",
    name: "Legendarisk Burkhjälm",
    price: 25,
    bonusHp: 5,
    damageNegate: 4,
    rulesText: "Ger +5 HP och −4 skada per träff när du har minst 15 klunkar.",
  },
  {
    id: "eh_beer_filled_helmet",
    slot: "helmet",
    name: "Ölfylld rymdhjälm",
    price: 12,
    combatBonus: 1,
    klunkAttackBonus10: 1,
    klunkAttackBonus20: 2,
    klunkAttackBonusMax: 3,
    rulesText: "Ju mer du druckit desto starkare blir du... konstigt nog.",
  },
  {
    id: "ex_buckler",
    slot: "accessory",
    name: "Burksköld",
    price: 8,
    damageNegate: 0,
    rulesText:
      "Burkset bonus: +1 / +2 / +3 sköld.",
  },
  {
    id: "ex_gold_chain",
    slot: "accessory",
    name: "Guldkedja",
    price: 9,
    gainGoldPerCombat: 1,
    rulesText: "Bling vid varje monsterstrid: lite pant när striden tar fart.",
  },
  {
    id: "ex_beer_cape",
    slot: "accessory",
    name: "Mantel",
    price: 9,
    canSkipMonsterEncounter: true,
    rulesText: "Skippa dålig batch. En dramatikens mästare. Ena sekunden är du där, nästa är du i kebabkön.",
  },
  {
    id: "ex_four_clover",
    slot: "accessory",
    name: "Fyrklöver",
    price: 11,
    ignoreCombatCritFailOnOne: true,
    rulesText: "Turtecken: etta på din stridstärning räknas inte som automatisk förlust.",
  },
  {
    id: "ex_sunglasses",
    slot: "accessory",
    name: "Solbrillor",
    price: 8,
    preventTheft: true,
    rulesText: "Ingen ser vad du har: andra kan inte stjäla dina prylar eller pant med stöld-effekter, och du skyddas vid BvB-byte.",
  },
  {
    id: "ex_tapkey",
    slot: "accessory",
    name: "Taproom nyckel",
    price: 7,
    levelUpDiscountGold: 10,
    rulesText: "VIP till nästa våning: det kostar mindre att gå upp en nivå.",
  },
  {
    id: "ex_ring",
    slot: "accessory",
    name: "Ring",
    price: 10,
    combatBonus: 2,
    damageNegate: -2,
    rulesText: "Priset för makt mäts sällan i guld, utan i blod. Är du redo att betala?",
  },
  {
    id: "ex_black_belt",
    slot: "accessory",
    name: "Svart bälte",
    price: 10,
    combatBonus: 1,
    penaltySipExtra: 1,
    rulesText:
      "Svart bälte i karatefylle: när du får straffklunk dricker du +1 extra klunk.",
  },
  {
    id: "ea_linne",
    slot: "armor",
    name: "Linne",
    price: 9,
    bonusHp: 0,
    combatBonus: 1,
    damageNegate: -1,
    rulesText: "Lätt och rörligt: du slår hårdare, men skyddet är sämre.",
  },
  {
    id: "ea_dunjacka",
    slot: "armor",
    name: "Dunjacka",
    price: 11,
    bonusHp: 5,
    combatBonus: -1,
    damageNegate: 0,
    rulesText: "Varm jacka som ger mycket extra HP, men gör dig lite mindre offensiv.",
  },
  {
    id: "ea_cap_bikini",
    slot: "armor",
    name: "Kapsylbikini",
    price: 9,
    bonusHp: 0,
    damageNegate: 1,
    pvpCannotBeChallenged: true,
    rulesText: "Avslappnad look: du kan inte utmanas till BvB, men du kan fortfarande utmana andra.",
  },
  {
    id: "ea_tshirt",
    slot: "armor",
    name: "T-shirt",
    price: 8,
    bonusHp: 0,
    damageNegate: 1,
    rulesText: "Basplagg med lätt skydd.",
  },
  {
    id: "ea_hoodie",
    slot: "armor",
    name: "Hoodie",
    price: 10,
    bonusHp: 0,
    damageNegate: 2,
    rulesText: "Mjuk och tjock — bättre skydd mot träffar.",
  },
  {
    id: "ea_six_pack",
    slot: "armor",
    name: "Sexpack",
    price: 11,
    bonusHp: 0,
    damageNegate: 1,
    gainGoldOnDamageTaken: 1,
    rulesText: "När du tar skada rullar en burk ut — lite pant som tröst.",
  },
  {
    id: "ea_beer_barrel",
    slot: "armor",
    name: "Öltunna",
    price: 13,
    bonusHp: 0,
    damageNegate: 2,
    healHpPerTurn: 1,
    rulesText: "+1 HP varje tur",
  },
  {
    id: "ea_can_armor",
    slot: "armor",
    name: "Burkrustning",
    price: 14,
    bonusHp: 0,
    damageNegate: 0,
    rulesText:
      "Burkset bonus: +2 / +4 / +10 max HP",
  },
];

