/** Publik sökväg till föremålsbild för kort, inventory och bräd-tv. */
export function itemImageSrc(itemId: string): string {
  const m: Record<string, string> = {
    healing_potion: "/items/healing-potion.webp",
    sleep_potion: "/items/sleep-potion.webp",
    sip_card: "/items/sip-card.webp",
    weak_beer: "/items/drunk-too-much.webp",
    light_beer: "/items/energy-drink.webp",
    folk_beer: "/items/8-bit-beer.webp",
    tripwire: "/items/tripwire.webp",
    pretzel_snack: "/items/brezel.webp",
    shortcut: "/items/shortcut.webp",
    taproom_key: "/equipment/accessory/taproom-nyckelring.webp",
    coin_purse: "/items/coin-purse.webp",
    double_hops: "/items/double-hops.webp",
    beer_bomb: "/items/beer-bomb.webp",
    beard_back: "/items/beard-back.webp",
    hangover: "/items/hangover.webp",
    monster_hype: "/items/monster-hype.webp",
    yeast_sabotage: "/items/yeast-sabotage.webp",
    beer_bro: "/items/beer-bro.webp",
    split_the_g: "/items/split-the-g.webp",
    lengraddad: "/event/lengraddad.webp",
    canman: "/items/canman.webp",
    not_my_round: "/items/not_my_round.webp",
    spill_intentional: "/items/spill_intentional.webp",
    early_night: "/items/item_early_night.webp",
    get_lucky: "/items/getlucky.webp",
    manopositiv: "/items/manopositiv.webp",
    six_sense: "/items/sixsense.webp",
    rigged_game: "/items/riggedgame.webp",
    bribes: "/items/bribes.webp",
    paidassasin: "/items/paidassasin.webp",
    charity: "/items/charity.webp",
    shuffle: "/items/shuffle.webp",
  };
  return m[itemId] ?? "/card-placeholder.png";
}
